#!/bin/bash

#sshtun core script, usable with a launchdaemon such as the one provided

#fill in data here, I recommend either setting pingip to the ip you want to connect to, or something like 8.8.8.8
#domain names work equally well
user=""
ip=""
pingip=""
port="22"
connected=0

if [[ $(whoami) == root ]];
then
	connected()
	{
		$( ping -q -c 2 -f $pingip > /dev/null 2>&1 )
	}
elif [[ $(whoami) != root ]]; then
	connected()
	{
		$( ping -q -c 2 $pingip > /dev/null 2>&1 )
	}
fi

tunnelcount()
{
	tunnelcount=$(ps -ax | grep ssh | grep -c $ip)
}

for (( i=1; i<=2; i++ ));
do
	if connected;
	then
		connected=1
		break
	else
		sleep 10
	fi
done

if [[ $connected -eq 1 ]];
	then
	for (( i=1; i<=3; i++ ));
	do
		tunnelcount
		if [ "$tunnelcount" -lt "1" ];
		then
			ssh "$user"@$ip -C -p "$port" -D 9999 -N -f -c blowfish
		elif [ "$tunnelcount" -eq "1" ];
		then
			break
		elif [ "$tunnelcount" -gt "1" ];
		then
			killall ssh
			((i--))
		fi
	done
fi