#!/bin/bash

#daemonized version of sshtun
#this checks every five minutes or so

#fill in data here, I recommend either setting pingip to the ip you want to connect to, or something like 8.8.8.8
#domain names work equally well
user=""
ip=""
pingip=""
port="22"
connected=0

if [[ $(whoami) == root ]];
then
	connected()
	{
		$( ping -q -c 2 -f $pingip > /dev/null 2>&1 )
	}
elif [[ $(whoami) != root ]]; then
	connected()
	{
		$( ping -q -c 2 $pingip > /dev/null 2>&1 )
	}
fi

tunnelcount()
{
	ps -ax | grep ssh | grep -c $ip
}

while(true);
do
	while ! connected;
	do
		sleep 300
		tunnelcount
		if [ "$tunnelcount" -ge "1" ];
		then
			if connected;
			then
				killall ssh
				break
			fi
		fi
	done

	for (( i=1; i<9; i++ ));
	do
		tunnelcount
		if [ "$tunnelcount" -lt "1" ];
		then
			ssh "$user"@$ip -C -p "$port" -D 9999 -N -f -c blowfish
			tunnelcount
			if [ "$tunnelcount" -ne "1" ];
			then
				((i+=3))
				sleep 2
			fi
		elif [ "$tunnelcount" -eq "1" ];
		then
			sleep 120
		elif [ "$tunnelcount" -gt "1" ];
		then
			killall ssh
			((i--))
		fi
	done
done